#ifndef __ARDUINO_PARKING_SENSOR_SETTINGS_H__
#define __ARDUINO_PARKING_SENSOR_SETTINGS_H__ 1

#define MAX_LISTENERS 4
#define MAX_SENSORS 2
#define MAX_EVENTS 2
#define MAX_STATES 7

#endif /* __ARDUINO_PARKING_SENSOR_SETTINGS_H__ */